---
artifacts:
- name: src
  source: .

- name: robot-software.git
  source: https://github.com/cvra/robot-software.git

- name: gcc-arm-embedded
  docker_image:
    context: robot-software.git/ci/dockerfiles/gcc-arm-embedded
  need:
    - robot-software.git

- name: build
  script: src/build.sh
  need:
    - src
    - robot-software.git
    - gcc-arm-embedded
